/* Generated by MyraPad at 3/22/2023 9:55:39 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;

namespace Test
{
	partial class WinTest: Window
	{
		private void BuildUI()
		{
			
			Title = "Hello";
			Content = null;
			Left = 440;
			Top = 173;
		}

		
	}
}
